### ISSUE TITLE
Fails to build with libglib2.0-dev:2.62.4

### ISSUE THREAD

**Issue by skvl** [tklengyel/drakvuf#851]
On Ubuntu 19.10 I got errors like this:
```
libdrakvuf.h:187:5: error: ‘GTimeVal’ is deprecated: Use 'GDateTime' instead [-Werror=deprecated-declarations]                                                                                
  187 |     GTimeVal timestamp;                                                                                                                                                               
      |     ^~~~~~~~                                                                           
```

There is no such error with `2.60.4`.

**Comment by skvl** [comment]
This works for me:
```
diff --git a/origin/src/Makefile.am b/origin/src/Makefile.am
index 96bba8a3..1bc43374 100644
--- a/origin/src/Makefile.am
+++ b/origin/src/Makefile.am
@@ -141,7 +141,9 @@ endif
 # Note that -pg is incompatible with HARDENING
 if DEBUG
 AM_CFLAGS += -DDRAKVUF_DEBUG -Werror -Wall -Wextra -g -ggdb3
+AM_CFLAGS += -Wno-deprecated-declarations
 AM_CXXFLAGS += -Wno-c99-designator -Wno-unknown-warning-option
+AM_CXXFLAGS += -Wno-deprecated-declarations
 AM_CXXFLAGS += -DDRAKVUF_DEBUG -Werror -Wall -Wextra -g -ggdb3
 AM_CXXFLAGS += -ferror-limit=0
 if !HARDENING
diff --git a/origin/src/libdrakvuf/Makefile.am b/origin/src/libdrakvuf/Makefile.am
index be995b6e..afc99eb0 100644
--- a/origin/src/libdrakvuf/Makefile.am
+++ b/origin/src/libdrakvuf/Makefile.am
@@ -143,6 +143,7 @@ AM_CFLAGS += -Wcast-qual -Wcast-align -Wstrict-aliasing \
              -Wmissing-prototypes -Wredundant-decls \
              -Wfloat-equal -Wundef -Wvla \
              -Wc++-compat
+AM_CFLAGS += -Wno-deprecated-declarations
 if !HARDENING
 AM_CFLAGS += -pg
 endif
diff --git a/origin/src/libinjector/Makefile.am b/origin/src/libinjector/Makefile.am
index 1c7817f3..d490d308 100644
--- a/origin/src/libinjector/Makefile.am
+++ b/origin/src/libinjector/Makefile.am
@@ -127,6 +127,7 @@ endif
 # Note that -pg is incompatible with HARDENING
 if DEBUG
 AM_CFLAGS += -DDRAKVUF_DEBUG -Wall -Wextra -Werror -g -ggdb3
+AM_CFLAGS += -Wno-deprecated-declarations
 if !HARDENING
 AM_CFLAGS += -pg
 endif
diff --git a/origin/src/libusermode/Makefile.am b/origin/src/libusermode/Makefile.am
index 28ba35a1..93a1da8d 100644
--- a/origin/src/libusermode/Makefile.am
+++ b/origin/src/libusermode/Makefile.am
@@ -127,6 +127,7 @@ AM_LDFLAGS += $(SANITIZE_LDFLAGS)
 endif
 
 if DEBUG
+AM_CXXFLAGS += -Wno-deprecated-declarations
 AM_CXXFLAGS += -DDRAKVUF_DEBUG -Werror -Wall -Wextra -g -ggdb3
 AM_CXXFLAGS += -Wno-unused-parameter
 AM_CXXFLAGS += -Wno-c99-designator -Wno-reorder-init-list -Wno-unknown-warning-option
diff --git a/origin/src/plugins/Makefile.am b/origin/src/plugins/Makefile.am
index 651aa736..22e7cf9a 100644
--- a/origin/src/plugins/Makefile.am
+++ b/origin/src/plugins/Makefile.am
@@ -281,6 +281,7 @@ AM_LDFLAGS += $(SANITIZE_LDFLAGS)
 endif
 
 if DEBUG
+AM_CXXFLAGS += -Wno-deprecated-declarations
 AM_CXXFLAGS += -DDRAKVUF_DEBUG -Werror -Wall -Wextra -g -ggdb3
 AM_CXXFLAGS += -ferror-limit=0
 AM_CXXFLAGS += -Wno-unused-parameter -Wno-unknown-warning-option
```

**Comment by tklengyel** [comment]
I would prefer if that warning stayed and instead we actually switched to using the recommended functions.
